joint_names:
  - mmrobot_joint1
  - mmrobot_joint2
  - mmrobot_joint3
  - mmrobot_joint4
  - mmrobot_joint5
  - mmrobot_joint6
  - mmrobot_joint7
arm_id: panda
# Activate rate limiter? [true|false]
rate_limiting: true
# Cutoff frequency of the low-pass filter. Set to >= 1000 to deactivate.
cutoff_frequency: 100
# Internal controller for motion generators [joint_impedance|cartesian_impedance]
internal_controller: joint_impedance
